/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'itemId' : IDL.Nat,
  'specialInstructions' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'preparationTimeMinutes' : IDL.Nat,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Record({ 'reason' : IDL.Text }),
  'pendingPayment' : IDL.Null,
  'rejected' : IDL.Record({ 'reason' : IDL.Text }),
  'confirmed' : IDL.Null,
  'paymentFailed' : IDL.Null,
});
export const ChefBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'eventDetails' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'updatedAt' : Time,
  'paymentReference' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'eventDate' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Record({ 'reason' : IDL.Text }),
  'outForDelivery' : IDL.Null,
  'completed' : IDL.Null,
  'pendingPayment' : IDL.Null,
  'rejected' : IDL.Record({ 'reason' : IDL.Text }),
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
  'paymentFailed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'statusHistory' : IDL.Vec(OrderStatus),
  'updatedAt' : Time,
  'specialInstructions' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'contactNumber' : IDL.Text,
  'paymentReference' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
});
export const DashboardMetrics = IDL.Record({
  'pendingBookings' : IDL.Vec(ChefBooking),
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Vec(Order),
  'recentOrders' : IDL.Vec(Order),
  'totalRevenue' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createChefBooking' : IDL.Func(
      [Time, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'getAcceptsCashOnDelivery' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAvailableItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getBookingIdsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getBookingStatus' : IDL.Func([IDL.Nat], [IDL.Opt(BookingStatus)], ['query']),
  'getBookingStatusText' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getBookingsByUser' : IDL.Func([], [IDL.Vec(ChefBooking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChefBooking' : IDL.Func([IDL.Nat], [IDL.Opt(ChefBooking)], ['query']),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getMenuCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderIdsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Opt(OrderStatus)], ['query']),
  'getOrderStatusHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OrderStatus)],
      ['query'],
    ),
  'getOrderStatusText' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getOrdersByUser' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSuccessfulOrderCountForToday' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAcceptsCashOnDelivery' : IDL.Func([IDL.Bool], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBookingPaymentRef' : IDL.Func(
      [IDL.Nat, IDL.Text, BookingStatus],
      [],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateMenuItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateOrderPaymentRef' : IDL.Func([IDL.Nat, IDL.Text, OrderStatus], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'itemId' : IDL.Nat,
    'specialInstructions' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'preparationTimeMinutes' : IDL.Nat,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Record({ 'reason' : IDL.Text }),
    'pendingPayment' : IDL.Null,
    'rejected' : IDL.Record({ 'reason' : IDL.Text }),
    'confirmed' : IDL.Null,
    'paymentFailed' : IDL.Null,
  });
  const ChefBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'eventDetails' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'updatedAt' : Time,
    'paymentReference' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'eventDate' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Record({ 'reason' : IDL.Text }),
    'outForDelivery' : IDL.Null,
    'completed' : IDL.Null,
    'pendingPayment' : IDL.Null,
    'rejected' : IDL.Record({ 'reason' : IDL.Text }),
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
    'paymentFailed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'statusHistory' : IDL.Vec(OrderStatus),
    'updatedAt' : Time,
    'specialInstructions' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'contactNumber' : IDL.Text,
    'paymentReference' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
  });
  const DashboardMetrics = IDL.Record({
    'pendingBookings' : IDL.Vec(ChefBooking),
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Vec(Order),
    'recentOrders' : IDL.Vec(Order),
    'totalRevenue' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createChefBooking' : IDL.Func(
        [Time, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'getAcceptsCashOnDelivery' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAvailableItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getBookingIdsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getBookingStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BookingStatus)],
        ['query'],
      ),
    'getBookingStatusText' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getBookingsByUser' : IDL.Func([], [IDL.Vec(ChefBooking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChefBooking' : IDL.Func([IDL.Nat], [IDL.Opt(ChefBooking)], ['query']),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getMenuCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderIdsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Opt(OrderStatus)], ['query']),
    'getOrderStatusHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OrderStatus)],
        ['query'],
      ),
    'getOrderStatusText' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getOrdersByUser' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSuccessfulOrderCountForToday' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAcceptsCashOnDelivery' : IDL.Func([IDL.Bool], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBookingPaymentRef' : IDL.Func(
        [IDL.Nat, IDL.Text, BookingStatus],
        [],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateMenuItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateOrderPaymentRef' : IDL.Func(
        [IDL.Nat, IDL.Text, OrderStatus],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };