/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingStatus = { 'cancelled' : { 'reason' : string } } |
  { 'pendingPayment' : null } |
  { 'rejected' : { 'reason' : string } } |
  { 'confirmed' : null } |
  { 'paymentFailed' : null };
export interface ChefBooking {
  'id' : bigint,
  'status' : BookingStatus,
  'eventDetails' : string,
  'createdAt' : Time,
  'user' : Principal,
  'updatedAt' : Time,
  'paymentReference' : [] | [string],
  'price' : bigint,
  'location' : string,
  'eventDate' : Time,
}
export interface DashboardMetrics {
  'pendingBookings' : Array<ChefBooking>,
  'totalOrders' : bigint,
  'pendingOrders' : Array<Order>,
  'recentOrders' : Array<Order>,
  'totalRevenue' : bigint,
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
  'preparationTimeMinutes' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'createdAt' : Time,
  'user' : Principal,
  'statusHistory' : Array<OrderStatus>,
  'updatedAt' : Time,
  'specialInstructions' : string,
  'totalAmount' : bigint,
  'contactNumber' : string,
  'paymentReference' : [] | [string],
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'itemId' : bigint,
  'specialInstructions' : string,
  'quantity' : bigint,
}
export type OrderStatus = { 'cancelled' : { 'reason' : string } } |
  { 'outForDelivery' : null } |
  { 'completed' : null } |
  { 'pendingPayment' : null } |
  { 'rejected' : { 'reason' : string } } |
  { 'confirmed' : null } |
  { 'inProgress' : null } |
  { 'paymentFailed' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<
    [string, string, bigint, string, string, boolean, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createChefBooking' : ActorMethod<[Time, string, string, bigint], bigint>,
  'createOrder' : ActorMethod<
    [Array<OrderItem>, string, string, string],
    bigint
  >,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getAllAvailableMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAvailableItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getBookingIdsByUser' : ActorMethod<[Principal], Array<bigint>>,
  'getBookingStatus' : ActorMethod<[bigint], [] | [BookingStatus]>,
  'getBookingStatusText' : ActorMethod<[bigint], string>,
  'getBookingsByUser' : ActorMethod<[], Array<ChefBooking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChefBooking' : ActorMethod<[bigint], [] | [ChefBooking]>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getMenuCategories' : ActorMethod<[], Array<string>>,
  'getMenuItem' : ActorMethod<[bigint], [] | [MenuItem]>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderIdsByUser' : ActorMethod<[Principal], Array<bigint>>,
  'getOrderStatus' : ActorMethod<[bigint], [] | [OrderStatus]>,
  'getOrderStatusHistory' : ActorMethod<[bigint], Array<OrderStatus>>,
  'getOrderStatusText' : ActorMethod<[bigint], string>,
  'getOrdersByUser' : ActorMethod<[], Array<Order>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSuccessfulOrderCountForToday' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingPaymentRef' : ActorMethod<
    [bigint, string, BookingStatus],
    undefined
  >,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, bigint, string, string, boolean, bigint],
    undefined
  >,
  'updateOrderPaymentRef' : ActorMethod<
    [bigint, string, OrderStatus],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];