/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export type BookingStatus = {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "pendingPayment";
    pendingPayment: null;
} | {
    __kind__: "rejected";
    rejected: {
        reason: string;
    };
} | {
    __kind__: "confirmed";
    confirmed: null;
} | {
    __kind__: "paymentFailed";
    paymentFailed: null;
};
export interface OrderItem {
    itemId: bigint;
    specialInstructions: string;
    quantity: bigint;
}
export interface ChefBooking {
    id: bigint;
    status: BookingStatus;
    eventDetails: string;
    createdAt: Time;
    user: Principal;
    updatedAt: Time;
    paymentReference?: string;
    price: bigint;
    location: string;
    eventDate: Time;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    createdAt: Time;
    user: Principal;
    statusHistory: Array<OrderStatus>;
    updatedAt: Time;
    specialInstructions: string;
    totalAmount: bigint;
    contactNumber: string;
    paymentReference?: string;
    items: Array<OrderItem>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MenuItem {
    id: bigint;
    name: string;
    createdAt: Time;
    isAvailable: boolean;
    description: string;
    imageUrl: string;
    category: string;
    price: bigint;
    preparationTimeMinutes: bigint;
}
export type OrderStatus = {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "outForDelivery";
    outForDelivery: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "pendingPayment";
    pendingPayment: null;
} | {
    __kind__: "rejected";
    rejected: {
        reason: string;
    };
} | {
    __kind__: "confirmed";
    confirmed: null;
} | {
    __kind__: "inProgress";
    inProgress: null;
} | {
    __kind__: "paymentFailed";
    paymentFailed: null;
};
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DashboardMetrics {
    pendingBookings: Array<ChefBooking>;
    totalOrders: bigint;
    pendingOrders: Array<Order>;
    recentOrders: Array<Order>;
    totalRevenue: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMenuItem(name: string, description: string, price: bigint, category: string, imageUrl: string, isAvailable: boolean, preparationTimeMinutes: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createChefBooking(eventDate: Time, location: string, eventDetails: string, price: bigint): Promise<bigint>;
    createOrder(items: Array<OrderItem>, deliveryAddress: string, contactNumber: string, specialInstructions: string): Promise<bigint>;
    deleteMenuItem(itemId: bigint): Promise<void>;
    getAllAvailableMenuItems(): Promise<Array<MenuItem>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAvailableItemsByCategory(category: string): Promise<Array<MenuItem>>;
    getBookingIdsByUser(user: Principal): Promise<Array<bigint>>;
    getBookingStatus(bookingId: bigint): Promise<BookingStatus | null>;
    getBookingStatusText(bookingId: bigint): Promise<string>;
    getBookingsByUser(): Promise<Array<ChefBooking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChefBooking(bookingId: bigint): Promise<ChefBooking | null>;
    getDashboardMetrics(): Promise<DashboardMetrics>;
    getMenuCategories(): Promise<Array<string>>;
    getMenuItem(itemId: bigint): Promise<MenuItem | null>;
    getMenuItemsByCategory(category: string): Promise<Array<MenuItem>>;
    getOrder(orderId: bigint): Promise<Order | null>;
    getOrderIdsByUser(user: Principal): Promise<Array<bigint>>;
    getOrderStatus(orderId: bigint): Promise<OrderStatus | null>;
    getOrderStatusHistory(orderId: bigint): Promise<Array<OrderStatus>>;
    getOrderStatusText(orderId: bigint): Promise<string>;
    getOrdersByUser(): Promise<Array<Order>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSuccessfulOrderCountForToday(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBookingPaymentRef(bookingId: bigint, paymentRef: string, newStatus: BookingStatus): Promise<void>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<void>;
    updateMenuItem(itemId: bigint, name: string, description: string, price: bigint, category: string, imageUrl: string, isAvailable: boolean, preparationTimeMinutes: bigint): Promise<void>;
    updateOrderPaymentRef(orderId: bigint, paymentRef: string, newStatus: OrderStatus): Promise<void>;
    updateOrderStatus(orderId: bigint, newStatus: OrderStatus): Promise<void>;
}
import type { BookingStatus as _BookingStatus, ChefBooking as _ChefBooking, DashboardMetrics as _DashboardMetrics, MenuItem as _MenuItem, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMenuItem(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: boolean, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createChefBooking(arg0: Time, arg1: string, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChefBooking(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChefBooking(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createOrder(arg0: Array<OrderItem>, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteMenuItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async getAllAvailableMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAvailableMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAvailableMenuItems();
            return result;
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return result;
        }
    }
    async getAvailableItemsByCategory(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableItemsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableItemsByCategory(arg0);
            return result;
        }
    }
    async getBookingIdsByUser(arg0: Principal): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingIdsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingIdsByUser(arg0);
            return result;
        }
    }
    async getBookingStatus(arg0: bigint): Promise<BookingStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingStatus(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingStatus(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingStatusText(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingStatusText(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingStatusText(arg0);
            return result;
        }
    }
    async getBookingsByUser(): Promise<Array<ChefBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByUser();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByUser();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChefBooking(arg0: bigint): Promise<ChefBooking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChefBooking(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChefBooking(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardMetrics(): Promise<DashboardMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics();
                return from_candid_DashboardMetrics_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics();
            return from_candid_DashboardMetrics_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuCategories();
            return result;
        }
    }
    async getMenuItem(arg0: bigint): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItemsByCategory(arg0: string): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemsByCategory(arg0);
            return result;
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderIdsByUser(arg0: Principal): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderIdsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderIdsByUser(arg0);
            return result;
        }
    }
    async getOrderStatus(arg0: bigint): Promise<OrderStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderStatus(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderStatus(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderStatusHistory(arg0: bigint): Promise<Array<OrderStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderStatusHistory(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderStatusHistory(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderStatusText(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderStatusText(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderStatusText(arg0);
            return result;
        }
    }
    async getOrdersByUser(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByUser();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByUser();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuccessfulOrderCountForToday(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuccessfulOrderCountForToday();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuccessfulOrderCountForToday();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBookingPaymentRef(arg0: bigint, arg1: string, arg2: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingPaymentRef(arg0, arg1, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingPaymentRef(arg0, arg1, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMenuItem(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: boolean, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateOrderPaymentRef(arg0: bigint, arg1: string, arg2: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderPaymentRef(arg0, arg1, to_candid_OrderStatus_n30(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderPaymentRef(arg0, arg1, to_candid_OrderStatus_n30(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ChefBooking_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChefBooking): ChefBooking {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardMetrics_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardMetrics): DashboardMetrics {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChefBooking]): ChefBooking | null {
    return value.length === 0 ? null : from_candid_ChefBooking_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderStatus]): OrderStatus | null {
    return value.length === 0 ? null : from_candid_OrderStatus_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingStatus]): BookingStatus | null {
    return value.length === 0 ? null : from_candid_BookingStatus_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingBookings: Array<_ChefBooking>;
    totalOrders: bigint;
    pendingOrders: Array<_Order>;
    recentOrders: Array<_Order>;
    totalRevenue: bigint;
}): {
    pendingBookings: Array<ChefBooking>;
    totalOrders: bigint;
    pendingOrders: Array<Order>;
    recentOrders: Array<Order>;
    totalRevenue: bigint;
} {
    return {
        pendingBookings: from_candid_vec_n6(_uploadFile, _downloadFile, value.pendingBookings),
        totalOrders: value.totalOrders,
        pendingOrders: from_candid_vec_n16(_uploadFile, _downloadFile, value.pendingOrders),
        recentOrders: from_candid_vec_n16(_uploadFile, _downloadFile, value.recentOrders),
        totalRevenue: value.totalRevenue
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    deliveryAddress: string;
    createdAt: _Time;
    user: Principal;
    statusHistory: Array<_OrderStatus>;
    updatedAt: _Time;
    specialInstructions: string;
    totalAmount: bigint;
    contactNumber: string;
    paymentReference: [] | [string];
    items: Array<_OrderItem>;
}): {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    createdAt: Time;
    user: Principal;
    statusHistory: Array<OrderStatus>;
    updatedAt: Time;
    specialInstructions: string;
    totalAmount: bigint;
    contactNumber: string;
    paymentReference?: string;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n19(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        createdAt: value.createdAt,
        user: value.user,
        statusHistory: from_candid_vec_n21(_uploadFile, _downloadFile, value.statusHistory),
        updatedAt: value.updatedAt,
        specialInstructions: value.specialInstructions,
        totalAmount: value.totalAmount,
        contactNumber: value.contactNumber,
        paymentReference: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.paymentReference)),
        items: value.items
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    eventDetails: string;
    createdAt: _Time;
    user: Principal;
    updatedAt: _Time;
    paymentReference: [] | [string];
    price: bigint;
    location: string;
    eventDate: _Time;
}): {
    id: bigint;
    status: BookingStatus;
    eventDetails: string;
    createdAt: Time;
    user: Principal;
    updatedAt: Time;
    paymentReference?: string;
    price: bigint;
    location: string;
    eventDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n4(_uploadFile, _downloadFile, value.status),
        eventDetails: value.eventDetails,
        createdAt: value.createdAt,
        user: value.user,
        updatedAt: value.updatedAt,
        paymentReference: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.paymentReference)),
        price: value.price,
        location: value.location,
        eventDate: value.eventDate
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: {
        reason: string;
    };
} | {
    outForDelivery: null;
} | {
    completed: null;
} | {
    pendingPayment: null;
} | {
    rejected: {
        reason: string;
    };
} | {
    confirmed: null;
} | {
    inProgress: null;
} | {
    paymentFailed: null;
}): {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "outForDelivery";
    outForDelivery: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "pendingPayment";
    pendingPayment: null;
} | {
    __kind__: "rejected";
    rejected: {
        reason: string;
    };
} | {
    __kind__: "confirmed";
    confirmed: null;
} | {
    __kind__: "inProgress";
    inProgress: null;
} | {
    __kind__: "paymentFailed";
    paymentFailed: null;
} {
    return "cancelled" in value ? {
        __kind__: "cancelled",
        cancelled: value.cancelled
    } : "outForDelivery" in value ? {
        __kind__: "outForDelivery",
        outForDelivery: value.outForDelivery
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "pendingPayment" in value ? {
        __kind__: "pendingPayment",
        pendingPayment: value.pendingPayment
    } : "rejected" in value ? {
        __kind__: "rejected",
        rejected: value.rejected
    } : "confirmed" in value ? {
        __kind__: "confirmed",
        confirmed: value.confirmed
    } : "inProgress" in value ? {
        __kind__: "inProgress",
        inProgress: value.inProgress
    } : "paymentFailed" in value ? {
        __kind__: "paymentFailed",
        paymentFailed: value.paymentFailed
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n27(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: {
        reason: string;
    };
} | {
    pendingPayment: null;
} | {
    rejected: {
        reason: string;
    };
} | {
    confirmed: null;
} | {
    paymentFailed: null;
}): {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "pendingPayment";
    pendingPayment: null;
} | {
    __kind__: "rejected";
    rejected: {
        reason: string;
    };
} | {
    __kind__: "confirmed";
    confirmed: null;
} | {
    __kind__: "paymentFailed";
    paymentFailed: null;
} {
    return "cancelled" in value ? {
        __kind__: "cancelled",
        cancelled: value.cancelled
    } : "pendingPayment" in value ? {
        __kind__: "pendingPayment",
        pendingPayment: value.pendingPayment
    } : "rejected" in value ? {
        __kind__: "rejected",
        rejected: value.rejected
    } : "confirmed" in value ? {
        __kind__: "confirmed",
        confirmed: value.confirmed
    } : "paymentFailed" in value ? {
        __kind__: "paymentFailed",
        paymentFailed: value.paymentFailed
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderStatus>): Array<OrderStatus> {
    return value.map((x)=>from_candid_OrderStatus_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChefBooking>): Array<ChefBooking> {
    return value.map((x)=>from_candid_ChefBooking_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "pendingPayment";
    pendingPayment: null;
} | {
    __kind__: "rejected";
    rejected: {
        reason: string;
    };
} | {
    __kind__: "confirmed";
    confirmed: null;
} | {
    __kind__: "paymentFailed";
    paymentFailed: null;
}): {
    cancelled: {
        reason: string;
    };
} | {
    pendingPayment: null;
} | {
    rejected: {
        reason: string;
    };
} | {
    confirmed: null;
} | {
    paymentFailed: null;
} {
    return value.__kind__ === "cancelled" ? {
        cancelled: value.cancelled
    } : value.__kind__ === "pendingPayment" ? {
        pendingPayment: value.pendingPayment
    } : value.__kind__ === "rejected" ? {
        rejected: value.rejected
    } : value.__kind__ === "confirmed" ? {
        confirmed: value.confirmed
    } : value.__kind__ === "paymentFailed" ? {
        paymentFailed: value.paymentFailed
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "outForDelivery";
    outForDelivery: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "pendingPayment";
    pendingPayment: null;
} | {
    __kind__: "rejected";
    rejected: {
        reason: string;
    };
} | {
    __kind__: "confirmed";
    confirmed: null;
} | {
    __kind__: "inProgress";
    inProgress: null;
} | {
    __kind__: "paymentFailed";
    paymentFailed: null;
}): {
    cancelled: {
        reason: string;
    };
} | {
    outForDelivery: null;
} | {
    completed: null;
} | {
    pendingPayment: null;
} | {
    rejected: {
        reason: string;
    };
} | {
    confirmed: null;
} | {
    inProgress: null;
} | {
    paymentFailed: null;
} {
    return value.__kind__ === "cancelled" ? {
        cancelled: value.cancelled
    } : value.__kind__ === "outForDelivery" ? {
        outForDelivery: value.outForDelivery
    } : value.__kind__ === "completed" ? {
        completed: value.completed
    } : value.__kind__ === "pendingPayment" ? {
        pendingPayment: value.pendingPayment
    } : value.__kind__ === "rejected" ? {
        rejected: value.rejected
    } : value.__kind__ === "confirmed" ? {
        confirmed: value.confirmed
    } : value.__kind__ === "inProgress" ? {
        inProgress: value.inProgress
    } : value.__kind__ === "paymentFailed" ? {
        paymentFailed: value.paymentFailed
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
